name: Lint

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Run linters
        uses: pre-commit/action@v2.0.0
