name: Build

on: [push, pull_request]

jobs:
  build:
    name: PyPI upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build twine wheel
      - name: Build distributions
        run: |
          python -m build
      - name: Publish package to PyPI
        if: github.repository == 'mastiggia/checkpatch-junit' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload --verbose -u '__token__' dist/*
